Update trigger_jenkins.yml

diff --git a/.github/workflows/trigger_jenkins.yml b/.github/workflows/trigger_jenkins.yml
--- a/.github/workflows/trigger_jenkins.yml
+++ b/.github/workflows/trigger_jenkins.yml
@@ -37,18 +37,32 @@ jobs:
           --header "Content-Type: application/json" \
           --data "$payload"
       shell: bash  
+    
+    - name: Delay for 60 seconds
+      run: |
+        sleep 60
+      shell: bash
         
     - name: Check Jenkins Job Status
       run: |
-        sleep 20
-        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
-        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/api/json?tree=builds[number,building,result,url]&pretty=true&tree=builds[number,result,url]&xpath=//build[actions/causes/shortDescription[text()='PR_NUMBER: ${PR_NUMBER}']][1]"
-        jenkins_job_status=$(curl -s "$jenkins_job_url" --user "shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}" | jq -r '.builds[0].result')
-        echo "Result is: $jenkins_job_status"
+        PR_NO=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
+        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/api/json?tree=builds[number,building,result,url]&pretty=true&tree=builds[number,result,url]&xpath=//build[actions/causes/shortDescription[text()=%27PR_NUMBER:%20${PR_NO}%27]][1]"
+        
+        jenkins_job_status="null"
+        while ["$jenkins_job_status" == "null"]; do
+          jenkins_job_status=$(curl -s "$jenkins_job_url" | jq -r '.builds[0].result')
+          if [[ "$jenkins_job_status" == "null"]; then
+            echo "Jenkins job is still in progress, waiting..."
+            sleep 10
+          fi
+        done
+
         if [ "$jenkins_job_status" == "FAILURE" ]; then
-        echo "Jenkins job failed"
-        exit 1
+          echo "Jenkins job failed"
+          exit 1
         elif [ "$jenkins_job_status" == "SUCCESS" ]; then
-        echo "Jenkins job succeeded"
+          echo "Jenkins job succeeded"
         fi
+
+      shell: bash
   
