Update trigger_jenkins.yml

diff --git a/.github/workflows/trigger_jenkins.yml b/.github/workflows/trigger_jenkins.yml
--- a/.github/workflows/trigger_jenkins.yml
+++ b/.github/workflows/trigger_jenkins.yml
@@ -15,3 +15,20 @@ jobs:
       run: |
         curl -vs "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test" \
         --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}
+        
+    - name: Check Jenkins Job Status
+      run: |
+        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/lastBuild/api/json"
+
+        while true; do
+          jenkins_job_status=$(curl -s "$jenkins_job_url" | jq -r '.result')
+          if [ "$jenkins_job_status" == "FAILURE" ]; then
+            echo "Jenkins job failed"
+            exit 1
+          elif [ "$jenkins_job_status" == "SUCCESS" ]; then
+            echo "Jenkins job succeeded"
+            break
+          fi
+          sleep 10
+        done
+      continue-on-error: true
